name: OCM Test Invite link Cernbox v2 to Cernbox v2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   cernbox
      sender_version:    v2
      receiver_platform: cernbox
      receiver_version:  v2
