name: OCM Test Invite link Ocmstub v1.0.0 to Cernbox v2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   ocmstub
      sender_version:    v1.0.0
      receiver_platform: cernbox
      receiver_version:  v2
