name: OCM Test Invite link Cernbox v2 to Nextcloud-sm v27.1.11-sm

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   cernbox
      sender_version:    v2
      receiver_platform: nextcloud-sm
      receiver_version:  v27.1.11-sm
