name: OCM Test Invite link Cernbox v2 to Ocis v5.0.9

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   cernbox
      sender_version:    v2
      receiver_platform: ocis
      receiver_version:  v5.0.9
