name: OCM Test Invite link Opencloud v2.3.0 to Cernbox v2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   opencloud
      sender_version:    v2.3.0
      receiver_platform: cernbox
      receiver_version:  v2
