name: OCM Test Invite link Ocis v7.1.2 to Cernbox v2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   ocis
      sender_version:    v7.1.2
      receiver_platform: cernbox
      receiver_version:  v2
