name: OCM Test Share with Ocmgo v1.0.0 to Nextcloud v32.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   ocmgo
      sender_version:    v1.0.0
      receiver_platform: nextcloud
      receiver_version:  v32.0.0
