name: OCM Test Share with Nextcloud v28.0.14 to Ocmgo v1.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   nextcloud
      sender_version:    v28.0.14
      receiver_platform: ocmgo
      receiver_version:  v1.0.0
