name: OCM Test Share with Ocmgo v1.0.0 to Ocmgo v1.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   ocmgo
      sender_version:    v1.0.0
      receiver_platform: ocmgo
      receiver_version:  v1.0.0
