name: OCM Test Wayf Nextcloud v33 to Cernbox v2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          wayf
      sender_platform:   nextcloud
      sender_version:    v33
      receiver_platform: cernbox
      receiver_version:  v2
